### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by BrianLusina** [IanGithegi/Python_Classes#2]
Update README to match purpose or repository. It should contain the following;
1. What is the repo about
2. Getting started and how to download any dependencies
3. Testing, how to run tests and purpose of tests
4. What is has been built with (not necessary)
5. Project title.

Refer to [this](https://gist.github.com/BrianLusina/3b96e2805c6e791ef304eb141e59146b) for reference

**Comment by IanGithegi** [comment]
Apologies the delay. I thought I had committed but it was in a different work environment. I have updated a couple of changes to the README.md file but will update it as we continue.Areas of versioning and contribution will be updated as we continue with the classes
